//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application1 {
    using DevSandbox.Web.Dynamic;
    
    
    public class Application1Application : DevSandbox.Web.Dynamic.Application {
        
        protected override void Initialize() {
            this.RegisterAction("/Login", typeof(MyDemoWebApp.LoginAction));
        }
    }
}
